### ISSUE TITLE
Demo Request

### ISSUE THREAD

**Issue by nakshatrasinghh** [huuquyet/expo-next-tamagui-monorepo#29]
Can there be an example of how APIs will be called? For example, using a querying library like RTK query or Tanstack query?

**Comment by huuquyet** [comment]
I think you should check the T4 stack https://github.com/timothymiller/t4-app with full API support.
I'm currently just use local storage, thanks for your considering.

**Comment by huuquyet** [comment]
Thanks. So I will close this issue.
