### ISSUE TITLE
env var

### ISSUE THREAD

**Issue by axelverglas** [huuquyet/expo-next-tamagui-monorepo#35]
hello,

How to use env var ?

Have a nice day

**Comment by huuquyet** [comment]
Hello,
I didn't use any env var in here. Thanks

**Comment by axelverglas** [comment]
yes I know but if I would like to use it how do I do it?

thanks for the response

**Comment by huuquyet** [comment]
Oh, you just create a `.env` file, then define var inside like `EXAMPLE=value`
Then you access that value with built-in `process.env.EXAMPLE` of nodejs or with `dotenv` lib
I don't remember exactly, so I always ask google, stackoverflow, bing, chatgpt...
Thanks for interesting question
